name: deploy

on:
  push:
    branches:
      - main
jobs:
  AUTO_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@main
        with:
          password: ${{ secrets.PASSWORD }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
